# Generated by Django 4.2.27 on 2026-02-12 07:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('activities', '0002_activitylike'),
        ('communities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('challenge_type', models.CharField(choices=[('distance', 'Distance'), ('duration', 'Duration'), ('count', 'Activity Count'), ('elevation', 'Elevation')], max_length=20)),
                ('contribution_scope', models.CharField(choices=[('collective', 'Collective'), ('individual', 'Individual')], max_length=20)),
                ('activity_types', models.JSONField(default=list, help_text='List of activity types that qualify, e.g. ["run","walk"]')),
                ('target_value', models.FloatField(help_text='Goal number (km, hours, count, or meters depending on type)')),
                ('target_unit', models.CharField(help_text='Display unit: km, hours, activities, meters', max_length=20)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='upcoming', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenges', to='communities.community')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_challenges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChallengeContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(help_text='The contributed amount (km, hours, 1, or meters)')),
                ('contributed_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_contributions', to='activities.activity')),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='communities.challenge')),
            ],
            options={
                'ordering': ['-contributed_at'],
            },
        ),
        migrations.CreateModel(
            name='ChallengeParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('total_contributed', models.FloatField(default=0, help_text="Running total of this user's contributions")),
                ('is_completed', models.BooleanField(default=False, help_text='Whether this participant hit the individual target')),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='communities.challenge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-total_contributed'],
                'unique_together': {('challenge', 'user')},
            },
        ),
        migrations.RemoveField(
            model_name='communitychallenge',
            name='community',
        ),
        migrations.RemoveField(
            model_name='communitychallenge',
            name='created_by',
        ),
        migrations.DeleteModel(
            name='ChallengeParticipation',
        ),
        migrations.DeleteModel(
            name='CommunityChallenge',
        ),
        migrations.AddField(
            model_name='challengecontribution',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='communities.challengeparticipant'),
        ),
        migrations.AlterUniqueTogether(
            name='challengecontribution',
            unique_together={('challenge', 'activity')},
        ),
        migrations.AddIndex(
            model_name='challenge',
            index=models.Index(fields=['community', 'status'], name='communities_communi_85a601_idx'),
        ),
        migrations.AddIndex(
            model_name='challenge',
            index=models.Index(fields=['start_date', 'end_date'], name='communities_start_d_808397_idx'),
        ),
    ]
