# Generated by Django 4.2.27 on 2026-02-18 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0002_challenge_challengecontribution_challengeparticipant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='is_route_challenge',
            field=models.BooleanField(default=False, help_text='Whether this is a route-based challenge with waypoints'),
        ),
        migrations.CreateModel(
            name='ChallengeRouteWaypoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('waypoint_type', models.CharField(choices=[('start', 'Start'), ('checkpoint', 'Checkpoint'), ('end', 'End')], max_length=20)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('name', models.CharField(blank=True, help_text='e.g. "Thamel Gate", "Ratna Park", typed or from geocoding', max_length=200)),
                ('radius_meters', models.PositiveIntegerField(default=50, help_text='How close (in meters) a user must be to register as reached')),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_waypoints', to='communities.challenge')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('challenge', 'order')},
            },
        ),
    ]
