# Generated by Django 4.2.27 on 2026-02-03 09:45

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("run", "Run"),
                            ("walk", "Walk"),
                            ("cycle", "Cycle"),
                            ("hike", "Hike"),
                        ],
                        default="run",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in_progress", "In Progress"),
                            ("paused", "Paused"),
                            ("completed", "Completed"),
                            ("discarded", "Discarded"),
                        ],
                        default="in_progress",
                        max_length=20,
                    ),
                ),
                (
                    "route",
                    django.contrib.gis.db.models.fields.LineStringField(
                        blank=True, geography=True, null=True, srid=4326
                    ),
                ),
                (
                    "start_point",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, geography=True, null=True, srid=4326
                    ),
                ),
                (
                    "end_point",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, geography=True, null=True, srid=4326
                    ),
                ),
                (
                    "masked_start_point",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True,
                        geography=True,
                        help_text="Start point with privacy zone offset applied",
                        null=True,
                        srid=4326,
                    ),
                ),
                (
                    "masked_end_point",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True,
                        geography=True,
                        help_text="End point with privacy zone offset applied",
                        null=True,
                        srid=4326,
                    ),
                ),
                (
                    "privacy_zone_radius",
                    models.IntegerField(
                        default=200,
                        help_text="Radius in meters to mask start/end points",
                    ),
                ),
                (
                    "distance",
                    models.FloatField(default=0, help_text="Total distance in meters"),
                ),
                (
                    "duration",
                    models.DurationField(
                        blank=True,
                        help_text="Total activity duration (excluding pauses)",
                        null=True,
                    ),
                ),
                (
                    "total_elapsed_time",
                    models.DurationField(
                        blank=True,
                        help_text="Total elapsed time including pauses",
                        null=True,
                    ),
                ),
                (
                    "average_pace",
                    models.FloatField(
                        blank=True,
                        help_text="Average pace in seconds per kilometer",
                        null=True,
                    ),
                ),
                (
                    "average_speed",
                    models.FloatField(
                        blank=True, help_text="Average speed in km/h", null=True
                    ),
                ),
                (
                    "max_speed",
                    models.FloatField(
                        blank=True, help_text="Maximum speed in km/h", null=True
                    ),
                ),
                (
                    "elevation_gain",
                    models.FloatField(
                        blank=True,
                        help_text="Total elevation gain in meters",
                        null=True,
                    ),
                ),
                (
                    "elevation_loss",
                    models.FloatField(
                        blank=True,
                        help_text="Total elevation loss in meters",
                        null=True,
                    ),
                ),
                (
                    "calories_burned",
                    models.FloatField(
                        blank=True, help_text="Estimated calories burned", null=True
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="When the activity started",
                    ),
                ),
                (
                    "finished_at",
                    models.DateTimeField(
                        blank=True, help_text="When the activity finished", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("public", "Public"),
                            ("followers", "Followers Only"),
                            ("private", "Private"),
                        ],
                        default="public",
                        max_length=20,
                    ),
                ),
                (
                    "hide_start_end",
                    models.BooleanField(
                        default=False,
                        help_text="Whether to hide/mask start and end points",
                    ),
                ),
                (
                    "weather_temp",
                    models.FloatField(
                        blank=True, help_text="Temperature in Celsius", null=True
                    ),
                ),
                ("weather_condition", models.CharField(blank=True, max_length=50)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Activities",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="ActivityPause",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("paused_at", models.DateTimeField()),
                ("resumed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pauses",
                        to="activities.activity",
                    ),
                ),
            ],
            options={
                "ordering": ["paused_at"],
            },
        ),
        migrations.CreateModel(
            name="GPSPoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                (
                    "location",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, geography=True, null=True, srid=4326
                    ),
                ),
                (
                    "elevation",
                    models.FloatField(
                        blank=True, help_text="Elevation/altitude in meters", null=True
                    ),
                ),
                ("timestamp", models.DateTimeField()),
                (
                    "accuracy",
                    models.FloatField(
                        blank=True, help_text="GPS accuracy in meters", null=True
                    ),
                ),
                (
                    "speed",
                    models.FloatField(
                        blank=True, help_text="Speed at this point in m/s", null=True
                    ),
                ),
                (
                    "heading",
                    models.FloatField(
                        blank=True, help_text="Heading/bearing in degrees", null=True
                    ),
                ),
                (
                    "activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gps_points",
                        to="activities.activity",
                    ),
                ),
            ],
            options={
                "ordering": ["timestamp"],
                "indexes": [
                    models.Index(
                        fields=["activity", "timestamp"],
                        name="activities__activit_a79bd3_idx",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="activity",
            index=models.Index(
                fields=["user", "-started_at"], name="activities__user_id_a54e1c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="activity",
            index=models.Index(fields=["status"], name="activities__status_b1bb4f_idx"),
        ),
        migrations.AddIndex(
            model_name="activity",
            index=models.Index(
                fields=["activity_type"], name="activities__activit_8e7970_idx"
            ),
        ),
    ]
