# Generated by Django 4.2.27 on 2026-02-05 05:06

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_user_profile_picture_followrequest_follow'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivacyZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name for this zone (e.g., Home, Work)', max_length=100)),
                ('center', django.contrib.gis.db.models.fields.PointField(geography=True, help_text='Center point of the privacy zone', srid=4326)),
                ('radius', models.PositiveIntegerField(default=200, help_text='Radius in meters to hide')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this zone is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='privacy_zones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Privacy Zone',
                'verbose_name_plural': 'Privacy Zones',
                'ordering': ['name'],
            },
        ),
    ]
