# Generated by Django 4.2.29 on 2026-04-11 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RankTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Bronze, Silver, Gold', max_length=50, unique=True)),
                ('min_lifetime_points', models.PositiveIntegerField(help_text='Points required to reach this tier', unique=True)),
                ('color_hex', models.CharField(default='#FFD700', help_text='Hex color code for the banner (e.g., #FFD700)', max_length=7)),
                ('icon_name', models.CharField(default='medal-outline', help_text='Ionicons name for the frontend', max_length=50)),
            ],
            options={
                'verbose_name': 'Rank Tier',
                'verbose_name_plural': 'Rank Tiers',
                'ordering': ['min_lifetime_points'],
            },
        ),
    ]
